name: 'Hackerspace Configuration'
type: module
core: 8.x
dependencies:
  - block
  - csv_serialization
  - ctools
  - entity_reference_revisions
  - field
  - field_group
  - file
  - image
  - link
  - menu_ui
  - node
  - paragraphs
  - path
  - pathauto
  - rest
  - s3fs_cors
  - serialization
  - system
  - taxonomy
  - telephone
  - text
  - user
  - userprotect
  - video_embed_field
  - views
  - views_data_export
