name: 'Hackerspace Configuration'
type: module
core: 8.x
dependencies:
  - entity_reference_revisions
  - field
  - field_group
  - file
  - image
  - link
  - menu_ui
  - node
  - paragraphs
  - path
  - taxonomy
  - text
  - user
  - video_embed_field
  - views
