name: 'Hackerspace Configuration'
type: module
core: 8.x
dependencies:
  - ctools
  - entity_reference_revisions
  - field
  - field_group
  - file
  - image
  - link
  - menu_ui
  - node
  - paragraphs
  - path
  - pathauto
  - s3fs_cors
  - taxonomy
  - telephone
  - text
  - user
  - user_default_page
  - userprotect
  - video_embed_field
  - views
